import { Job, Employer } from '@/types'

export const sampleEmployers: Omit<Employer, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: "Grand Velas Resorts",
    description: "Cadena de resorts de lujo todo incluido con presencia en los destinos más exclusivos de México. Reconocidos por nuestro servicio excepcional y experiencias gastronómicas de clase mundial.",
    website: "https://grandvelas.com",
    email: "careers@grandvelas.com",
    phone: "+52 55 1234-5678",
    industry: "hoteleria",
    size: "1000+",
    location: "Riviera Maya",
    state: "Quintana Roo",
    founded: 1998,
    benefits: [
      "Seguro médico completo",
      "Descuentos en propiedades del grupo",
      "Capacitación continua",
      "Oportunidades de crecimiento internacional",
      "Programa de reconocimiento al empleado"
    ],
    culture: "Cultura de excelencia, pasión por el servicio y compromiso con el desarrollo personal y profesional de nuestro equipo.",
    mission: "Crear experiencias memorables que superen las expectativas de nuestros huéspedes.",
    vision: "Ser la cadena de resorts de lujo más reconocida de México por su excelencia en servicio.",
    values: ["Excelencia", "Pasión", "Respeto", "Integridad", "Innovación"],
    socialMedia: {
      linkedin: "https://linkedin.com/company/grand-velas",
      facebook: "https://facebook.com/grandvelas",
      instagram: "https://instagram.com/grandvelas"
    },
    verified: true,
    featured: true,
    premium: true,
    rating: 4.8,
    reviewsCount: 156,
    jobsCount: 12
  },
  {
    name: "Xcaret Experiencias",
    description: "Empresa líder en parques temáticos y experiencias turísticas en México, comprometida con la preservación cultural y ecológica de nuestro país.",
    website: "https://xcaret.com",
    email: "empleos@xcaret.com",
    phone: "+52 984 206-0038",
    industry: "entretenimiento",
    size: "201-1000",
    location: "Playa del Carmen",
    state: "Quintana Roo",
    founded: 1990,
    benefits: [
      "Seguro de vida y gastos médicos mayores",
      "Fondo de ahorro",
      "Acceso gratuito a parques",
      "Transporte empresarial",
      "Capacitación especializada",
      "Programa de bienestar integral"
    ],
    culture: "Somos una gran familia comprometida con México, su cultura y naturaleza. Promovemos el desarrollo profesional en un ambiente de respeto y colaboración.",
    mission: "Ofrecer experiencias únicas que conecten a las personas con la cultura y naturaleza de México.",
    vision: "Ser el grupo de entretenimiento más importante de México y referente mundial en turismo sustentable.",
    values: ["Amor por México", "Respeto por la naturaleza", "Excelencia", "Trabajo en equipo", "Innovación"],
    verified: true,
    featured: true,
    premium: true,
    rating: 4.6,
    reviewsCount: 203,
    jobsCount: 18
  },
  {
    name: "Viajes El Corte Inglés México",
    description: "Agencia de viajes líder con más de 40 años de experiencia, especializada en turismo corporativo, de placer y MICE. Parte del grupo El Corte Inglés de España.",
    website: "https://viajeselcorteingles.com.mx",
    email: "rrhh@viajeselcorteingles.com.mx",
    industry: "agencias-viajes",
    size: "51-200",
    location: "Ciudad de México",
    state: "Ciudad de México",
    founded: 1983,
    benefits: [
      "Seguro médico",
      "Prima vacacional",
      "Descuentos en viajes",
      "Capacitación internacional",
      "Horario flexible",
      "Home office híbrido"
    ],
    culture: "Equipo profesional y dinámico enfocado en brindar el mejor servicio al cliente con pasión por los viajes y la excelencia operativa.",
    verified: true,
    featured: false,
    premium: false,
    rating: 4.3,
    reviewsCount: 87,
    jobsCount: 6
  },
  {
    name: "Hotel Belmond Maroma",
    description: "Resort de lujo boutique ubicado en una de las playas más hermosas del Caribe mexicano, reconocido internacionalmente por su servicio personalizado y gastronomía excepcional.",
    website: "https://belmond.com",
    email: "careers.maroma@belmond.com",
    industry: "hoteleria",
    size: "201-1000",
    location: "Riviera Maya",
    state: "Quintana Roo",
    founded: 1995,
    benefits: [
      "Seguro médico internacional",
      "Programa de capacitación Belmond Academy",
      "Oportunidades de intercambio internacional",
      "Descuentos en propiedades Belmond mundialmente",
      "Programa de wellness para empleados"
    ],
    culture: "Cultivamos una cultura de hospitalidad auténtica donde cada miembro del equipo es embajador de experiencias extraordinarias.",
    verified: true,
    featured: true,
    premium: true,
    rating: 4.9,
    reviewsCount: 74,
    jobsCount: 8
  },
  {
    name: "Turismo Aventura México",
    description: "Operador turístico especializado en turismo de aventura y ecoturismo, ofreciendo experiencias únicas en los ecosistemas más diversos de México.",
    email: "jobs@aventuramexico.com",
    industry: "turismo-aventura",
    size: "11-50",
    location: "Puerto Vallarta",
    state: "Jalisco",
    founded: 2010,
    benefits: [
      "Seguro de vida",
      "Equipo especializado incluido",
      "Certificaciones internacionales",
      "Viajes de familiarización",
      "Participación en utilidades"
    ],
    culture: "Equipo apasionado por la aventura y el respeto a la naturaleza, comprometido con el turismo sustentable.",
    verified: false,
    featured: false,
    premium: false,
    rating: 4.4,
    reviewsCount: 32,
    jobsCount: 4
  }
]

export const sampleJobs: Omit<Job, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: "Gerente de Recepción",
    company: "Grand Velas Resorts",
    employerId: "employer1", // Will be replaced with actual IDs
    location: "Riviera Maya",
    state: "Quintana Roo",
    type: "tiempo-completo",
    category: "hoteleria",
    salary: {
      min: 25000,
      max: 35000,
      currency: "MXN",
      period: "mes"
    },
    description: "Únete a nuestro equipo como Gerente de Recepción en uno de los resorts más exclusivos de la Riviera Maya. Serás responsable de liderar el equipo de recepción y garantizar una experiencia excepcional a nuestros huéspedes VIP.\n\nTrabajando en un ambiente de lujo, tendrás la oportunidad de desarrollar tus habilidades de liderazgo mientras brindas el más alto nivel de servicio personalizado.",
    requirements: [
      "Licenciatura en Hotelería, Turismo o afín",
      "Mínimo 3 años de experiencia en posiciones similares en hoteles 5 estrellas",
      "Inglés avanzado (indispensable)",
      "Manejo de sistemas hoteleros (Opera, PMS)",
      "Excelentes habilidades de comunicación y liderazgo",
      "Disponibilidad de horarios rotativos"
    ],
    responsibilities: [
      "Supervisar las operaciones diarias del departamento de recepción",
      "Garantizar los estándares de servicio de lujo del resort",
      "Liderar, capacitar y motivar al equipo de recepcionistas",
      "Manejar situaciones especiales y quejas de huéspedes VIP",
      "Coordinar con otros departamentos para optimizar la experiencia del huésped",
      "Preparar reportes operativos y de ocupación",
      "Implementar procesos de mejora continua"
    ],
    benefits: [
      "Sueldo competitivo + bonos por desempeño",
      "Seguro médico completo para empleado y familia",
      "Descuentos del 50% en propiedades del grupo",
      "Programa de capacitación continua internacional",
      "Oportunidades de crecimiento dentro del grupo",
      "Comedor subsidiado",
      "Transporte empresarial"
    ],
    skills: ["Liderazgo", "Servicio al cliente", "Opera PMS", "Inglés avanzado", "Resolución de problemas"],
    experience: "3-5 años en hotelería de lujo",
    education: "Licenciatura en Hotelería, Turismo o carrera afín",
    languages: ["Español (nativo)", "Inglés (avanzado)"],
    tags: ["liderazgo", "lujo", "internacional"],
    remote: false,
    urgent: false,
    featured: true,
    verified: true,
    status: "active",
    views: 245,
    applications: 18,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) // 30 days from now
  },
  {
    title: "Guía Bilingüe de Experiencias Culturales",
    company: "Xcaret Experiencias",
    employerId: "employer2",
    location: "Playa del Carmen",
    state: "Quintana Roo",
    type: "tiempo-completo",
    category: "guias-turisticos",
    salary: {
      min: 18000,
      max: 25000,
      currency: "MXN",
      period: "mes"
    },
    description: "Buscamos guías apasionados por la cultura mexicana para crear experiencias memorables en nuestros parques temáticos. Serás el embajador de nuestras tradiciones y naturaleza ante visitantes de todo el mundo.\n\nEsta es una oportunidad única para combinar tu amor por México con el turismo sustentable, trabajando en el grupo de entretenimiento más importante del país.",
    requirements: [
      "Licenciatura en Turismo, Historia, Antropología o afín",
      "Inglés avanzado conversacional (indispensable)",
      "Conocimientos sólidos sobre cultura e historia mexicana",
      "Experiencia mínima de 1 año como guía turístico",
      "Excelente condición física",
      "Facilidad de palabra y carisma",
      "Disponibilidad de horarios y días de la semana"
    ],
    responsibilities: [
      "Conducir tours culturales y naturales en español e inglés",
      "Narrar la historia y tradiciones de México de manera entretenida",
      "Garantizar la seguridad y satisfacción de los visitantes",
      "Promover la conciencia ecológica y cultural",
      "Colaborar con diferentes áreas para optimizar experiencias",
      "Mantener actualizados los conocimientos sobre atracciones",
      "Participar en capacitaciones y certificaciones continuas"
    ],
    benefits: [
      "Sueldo base + comisiones por ventas adicionales",
      "Seguro de vida y gastos médicos",
      "Acceso gratuito a todos los parques Xcaret",
      "Transporte gratuito desde Cancún y Playa del Carmen",
      "Uniformes y equipo incluidos",
      "Programa de capacitación especializada",
      "Oportunidades de crecimiento profesional"
    ],
    skills: ["Guía turístico", "Inglés avanzado", "Historia de México", "Comunicación", "Liderazgo de grupos"],
    experience: "1-3 años en turismo cultural",
    education: "Licenciatura en Turismo, Historia o afín",
    languages: ["Español (nativo)", "Inglés (avanzado)", "Francés (básico - deseable)"],
    tags: ["cultura", "bilingüe", "naturaleza"],
    remote: false,
    urgent: true,
    featured: true,
    verified: true,
    status: "active",
    views: 189,
    applications: 24,
    expiresAt: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000) // 21 days from now
  },
  {
    title: "Consultor de Viajes Corporativos",
    company: "Viajes El Corte Inglés México",
    employerId: "employer3",
    location: "Ciudad de México",
    state: "Ciudad de México",
    type: "tiempo-completo",
    category: "agencias-viajes",
    salary: {
      min: 20000,
      max: 28000,
      currency: "MXN",
      period: "mes"
    },
    description: "Oportunidad para profesional del turismo con experiencia en viajes corporativos. Serás responsable de asesorar a empresas clientes en la planificación y gestión de sus viajes de negocios, eventos y convenciones.\n\nTrabaja con las mejores empresas de México brindando soluciones integrales de turismo corporativo con el respaldo de una marca internacional líder.",
    requirements: [
      "Licenciatura en Turismo, Administración o carrera afín",
      "Mínimo 2 años de experiencia en viajes corporativos",
      "Inglés intermedio-avanzado",
      "Conocimiento de GDS Amadeus (deseable)",
      "Excelente atención al cliente",
      "Habilidades de negociación",
      "Proactividad y orientación a resultados"
    ],
    responsibilities: [
      "Asesorar a clientes corporativos en planificación de viajes",
      "Cotizar y reservar servicios turísticos integrales",
      "Mantener y desarrollar cartera de clientes empresariales",
      "Negociar tarifas con proveedores hoteleros y aerolíneas",
      "Coordinar eventos corporativos y convenciones",
      "Elaborar reportes de gastos de viaje para empresas",
      "Brindar soporte 24/7 durante viajes corporativos"
    ],
    benefits: [
      "Sueldo base + comisiones por ventas",
      "Seguro médico",
      "Prima vacacional superior a la ley",
      "Descuentos especiales en viajes personales",
      "Capacitación en nuevos destinos (viajes de familiarización)",
      "Horario flexible",
      "Modalidad híbrida (home office 2 días por semana)"
    ],
    skills: ["GDS Amadeus", "Viajes corporativos", "Negociación", "Excel avanzado", "CRM"],
    experience: "2-4 años en turismo corporativo",
    education: "Licenciatura en Turismo o Administración",
    languages: ["Español (nativo)", "Inglés (intermedio-avanzado)"],
    tags: ["corporativo", "b2b", "negociación"],
    remote: false,
    urgent: false,
    featured: false,
    verified: true,
    status: "active",
    views: 156,
    applications: 12,
    expiresAt: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000)
  },
  {
    title: "Chef de Partida - Cocina Gourmet",
    company: "Hotel Belmond Maroma",
    employerId: "employer4",
    location: "Riviera Maya",
    state: "Quintana Roo",
    type: "tiempo-completo",
    category: "restauracion",
    salary: {
      min: 22000,
      max: 30000,
      currency: "MXN",
      period: "mes"
    },
    description: "Únete al equipo culinario de uno de los resorts más exclusivos del Caribe mexicano. Buscamos un Chef de Partida talentoso para nuestro restaurante gourmet, donde crearás experiencias gastronómicas excepcionales para huéspedes internacionales.\n\nTrabaja bajo la mentoría de chefs internacionales en un ambiente de alta cocina con ingredientes premium y técnicas vanguardistas.",
    requirements: [
      "Título en Gastronomía o Artes Culinarias",
      "Mínimo 3 años de experiencia en cocina gourmet",
      "Experiencia en hoteles 5 estrellas o restaurantes fine dining",
      "Conocimiento de técnicas culinarias internacionales",
      "Inglés básico-intermedio",
      "Disponibilidad de horarios rotativos",
      "Pasión por la alta cocina y la innovación"
    ],
    responsibilities: [
      "Preparar platillos gourmet según estándares Belmond",
      "Mantener la calidad y presentación excepcional de los alimentos",
      "Colaborar en el desarrollo de menús estacionales",
      "Supervisar el mise en place de su estación",
      "Mantener los estándares de higiene y seguridad alimentaria",
      "Entrenar a cocineros junior en técnicas especializadas",
      "Participar en cenas temáticas y eventos especiales"
    ],
    benefits: [
      "Sueldo competitivo en resort de lujo",
      "Seguro médico internacional",
      "Capacitación con chefs internacionales",
      "Descuentos en propiedades Belmond mundialmente",
      "Comidas gourmet incluidas",
      "Programa de intercambio internacional",
      "Crecimiento profesional acelerado"
    ],
    skills: ["Cocina gourmet", "Fine dining", "Técnicas francesas", "Presentación", "Innovación culinaria"],
    experience: "3-5 años en alta cocina",
    education: "Título en Gastronomía",
    languages: ["Español (nativo)", "Inglés (intermedio)", "Francés (básico - deseable)"],
    tags: ["gourmet", "lujo", "internacional"],
    remote: false,
    urgent: false,
    featured: true,
    verified: true,
    status: "active",
    views: 134,
    applications: 15,
    expiresAt: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000)
  },
  {
    title: "Coordinador de Turismo de Aventura",
    company: "Turismo Aventura México",
    employerId: "employer5",
    location: "Puerto Vallarta",
    state: "Jalisco",
    type: "tiempo-completo",
    category: "turismo-aventura",
    salary: {
      min: 16000,
      max: 22000,
      currency: "MXN",
      period: "mes"
    },
    description: "Oportunidad para profesional apasionado por la aventura y el ecoturismo. Coordinarás actividades de turismo de aventura en los ecosistemas más increíbles de Jalisco, desde la sierra hasta la costa.\n\nSerás parte de un equipo comprometido con el turismo sustentable y la conservación, creando experiencias transformadoras para viajeros aventureros.",
    requirements: [
      "Licenciatura en Turismo, Biología o carrera afín",
      "Experiencia mínima de 2 años en turismo de aventura",
      "Certificaciones en actividades outdoor (rapel, kayak, senderismo)",
      "Inglés intermedio",
      "Excelente condición física",
      "Conocimiento de primeros auxilios",
      "Licencia de conducir vigente"
    ],
    responsibilities: [
      "Coordinar tours de aventura y ecoturismo",
      "Garantizar la seguridad de los participantes en todo momento",
      "Mantener y revisar equipo especializado",
      "Capacitar a guías en protocolos de seguridad",
      "Desarrollar nuevas rutas y experiencias",
      "Promover prácticas de turismo sustentable",
      "Mantener relaciones con comunidades locales"
    ],
    benefits: [
      "Sueldo base + bonos por tours adicionales",
      "Seguro de vida y accidentes",
      "Todo el equipo especializado incluido",
      "Certificaciones internacionales pagadas por la empresa",
      "Viajes de exploración para nuevas rutas",
      "Participación en utilidades",
      "Ambiente de trabajo al aire libre"
    ],
    skills: ["Turismo de aventura", "Primeros auxilios", "Liderazgo de grupos", "Seguridad outdoor", "Ecoturismo"],
    experience: "2-4 años en turismo aventura",
    education: "Licenciatura en Turismo o Biología",
    languages: ["Español (nativo)", "Inglés (intermedio)"],
    tags: ["aventura", "naturaleza", "sustentable"],
    remote: false,
    urgent: false,
    featured: false,
    verified: false,
    status: "active",
    views: 98,
    applications: 8,
    expiresAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000)
  },
  {
    title: "Practicante de Marketing Digital Turístico",
    company: "Grand Velas Resorts",
    employerId: "employer1",
    location: "Riviera Maya",
    state: "Quintana Roo",
    type: "practicas",
    category: "marketing-turistico",
    salary: {
      min: 8000,
      max: 10000,
      currency: "MXN",
      period: "mes"
    },
    description: "Oportunidad única para estudiante o recién egresado de Marketing o Turismo. Aprenderás marketing digital en la industria hotelera de lujo, trabajando con campañas internacionales para mercados de alto valor.\n\nEsta práctica profesional te permitirá desarrollar habilidades especializadas en marketing turístico digital con mentores expertos en la industria.",
    requirements: [
      "Estudiante de últimos semestres o recién egresado",
      "Carrera en Marketing, Comunicación, Turismo o afín",
      "Conocimientos básicos de marketing digital",
      "Manejo de redes sociales",
      "Inglés intermedio",
      "Creatividad y proactividad",
      "Disponibilidad tiempo completo por 6 meses mínimo"
    ],
    responsibilities: [
      "Apoyar en la creación de contenido para redes sociales",
      "Participar en campañas de marketing digital",
      "Realizar análisis de métricas y reportes",
      "Colaborar en la organización de eventos y activaciones",
      "Aprender sobre segmentación de mercados internacionales",
      "Apoyar en la coordinación con influencers y travel bloggers",
      "Participar en sesiones de capacitación especializadas"
    ],
    benefits: [
      "Beca mensual competitiva",
      "Carta de recomendación al finalizar exitosamente",
      "Capacitación especializada en marketing hotelero",
      "Acceso a descuentos en propiedades del grupo",
      "Posibilidad de contratación directa",
      "Mentoring con profesionales senior",
      "Experiencia internacional invaluable"
    ],
    skills: ["Marketing digital", "Redes sociales", "Analytics", "Creatividad", "Inglés"],
    experience: "Sin experiencia - Nivel de entrada",
    education: "Estudiante o pasante en Marketing/Turismo",
    languages: ["Español (nativo)", "Inglés (intermedio)"],
    tags: ["practicas", "marketing", "digital"],
    remote: false,
    urgent: true,
    featured: false,
    verified: true,
    status: "active",
    views: 267,
    applications: 34,
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000) // 2 weeks
  }
]